name: just_audio_dart_vlc
description: just_audio plugin to use dart_vlc
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dart_vlc: ^0.1.9
  flutter:
    sdk: flutter
  just_audio_platform_interface: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: none
        dartPluginClass: DartVlcJustAudioPlatform
      windows:
        pluginClass: none
        dartPluginClass: DartVlcJustAudioPlatform
